# Generated by Django 3.1.4 on 2020-12-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastapi_table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('object_type', models.CharField(max_length=10)),
                ('object_last_updated', models.CharField(max_length=23)),
                ('score', models.CharField(max_length=7)),
                ('severity', models.CharField(max_length=6)),
                ('comm_count', models.IntegerField()),
                ('ref_count', models.IntegerField()),
            ],
        ),
    ]
