# Generated by Django 3.1.4 on 2021-01-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastapi_table', '0002_domainip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionParents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.CharField(max_length=64)),
                ('related_file_id', models.CharField(max_length=64)),
                ('exec_date_scanned', models.CharField(max_length=23)),
                ('detection_score', models.CharField(max_length=7)),
                ('severity', models.CharField(max_length=6)),
                ('parent_type', models.CharField(max_length=255)),
            ],
        ),
    ]
