# Generated by Django 3.1.4 on 2021-01-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastapi_table', '0003_executionparents'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicatingFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_file_id', models.CharField(max_length=64)),
                ('comm_file_name', models.TextField()),
                ('related_object_id', models.CharField(max_length=255)),
                ('date_scanned', models.CharField(max_length=23)),
                ('detection_score', models.CharField(max_length=7)),
                ('severity', models.CharField(max_length=6)),
                ('comm_file_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ReferrerFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_file_id', models.CharField(max_length=64)),
                ('ref_file_name', models.TextField()),
                ('related_object_id', models.CharField(max_length=255)),
                ('date_scanned', models.CharField(max_length=23)),
                ('detection_score', models.CharField(max_length=7)),
                ('severity', models.CharField(max_length=6)),
                ('ref_file_type', models.CharField(max_length=255)),
            ],
        ),
    ]
